[package]
name = "compiler"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "n2tcc"
path = "src/main.rs"

[dependencies]
compact_str = "0.7.0"
regex = "1"
lazy_static = "1.4.0"
clap = { version = "4.0", features = ["derive"]}
normalize-line-endings = "0.3.0"
